const TravelListingData = {
  location: "Cox's Bazar, Bangladesh",
  totalResults: 127,
  currentPage: 1,
  totalPages: 11,
  packages: [
    {
      id: "1",
      title: "Cox's Bazar Beach Adventure Tour",
      image: "/assets/images/packages/p1-1.webp",
      location: "Cox's Bazar, Bangladesh",
      duration: "3 Days",
      groupSize: "2-12 People",
      price: 120,
      originalPrice: 150,
      rating: 4.8,
      reviewCount: 127,
      category: "Adventure Tours",
      isFavorite: false,
      features: ["Beach Activities", "Local Guide", "Transportation", "Accommodation"],
      description: "Experience the longest sea beach in the world with our comprehensive tour package.",
      highlights: ["World's Longest Beach", "Local Culture", "Adventure Activities"],
      inclusions: ["Transportation", "Guide", "Meals", "Accommodation"],
      exclusions: ["Personal Expenses", "Optional Activities"],
      cancellationPolicy: "Free cancellation up to 24 hours before tour",
      instantConfirmation: true,
      bestPriceGuarantee: true
    },
    {
      id: "2",
      title: "St. Martin Island Day Trip",
      image: "/assets/images/packages/p1-2.webp",
      location: "St. Martin Island, Bangladesh",
      duration: "1 Day",
      groupSize: "4-15 People",
      price: 85,
      rating: 4.6,
      reviewCount: 89,
      category: "Day Trips",
      isFavorite: true,
      features: ["Boat Ride", "Snorkeling", "Lunch Included", "Island Exploration"],
      description: "Discover the only coral island of Bangladesh with crystal clear waters.",
      highlights: ["Coral Island", "Snorkeling", "Boat Ride"],
      inclusions: ["Boat Transfer", "Lunch", "Snorkeling Equipment"],
      exclusions: ["Personal Items", "Additional Activities"],
      cancellationPolicy: "Free cancellation up to 12 hours before tour",
      instantConfirmation: true,
      bestPriceGuarantee: true
    },
    {
      id: "3",
      title: "Cox's Bazar Cultural Heritage Tour",
      image: "/assets/images/packages/p1-3.webp",
      location: "Cox's Bazar, Bangladesh",
      duration: "2 Days",
      groupSize: "2-8 People",
      price: 95,
      rating: 4.7,
      reviewCount: 156,
      category: "Cultural Tours",
      isFavorite: false,
      features: ["Local Markets", "Traditional Food", "Cultural Sites", "Local Guide"],
      description: "Immerse yourself in the rich cultural heritage of Cox's Bazar region.",
      highlights: ["Local Markets", "Traditional Cuisine", "Cultural Sites"],
      inclusions: ["Guide", "Transportation", "Meals", "Entrance Fees"],
      exclusions: ["Personal Shopping", "Optional Activities"],
      cancellationPolicy: "Free cancellation up to 24 hours before tour",
      instantConfirmation: true,
      bestPriceGuarantee: true
    },
    {
      id: "4",
      title: "Inani Beach & Himchari Waterfall",
      image: "/assets/images/packages/p1-4.webp",
      location: "Inani Beach, Bangladesh",
      duration: "1 Day",
      groupSize: "2-10 People",
      price: 75,
      originalPrice: 90,
      rating: 4.5,
      reviewCount: 203,
      category: "Nature Tours",
      isFavorite: false,
      features: ["Waterfall Visit", "Beach Time", "Photography", "Nature Walk"],
      description: "Explore the pristine Inani Beach and witness the beautiful Himchari Waterfall.",
      highlights: ["Waterfall", "Pristine Beach", "Nature Photography"],
      inclusions: ["Transportation", "Guide", "Lunch"],
      exclusions: ["Personal Items", "Camera Equipment"],
      cancellationPolicy: "Free cancellation up to 12 hours before tour",
      instantConfirmation: true,
      bestPriceGuarantee: true
    },
    {
      id: "5",
      title: "Cox's Bazar Food & Street Tour",
      image: "/assets/images/packages/p1-5.webp",
      location: "Cox's Bazar, Bangladesh",
      duration: "Half Day",
      groupSize: "2-6 People",
      price: 45,
      rating: 4.9,
      reviewCount: 78,
      category: "Food Tours",
      isFavorite: true,
      features: ["Local Cuisine", "Street Food", "Cultural Experience", "Food Guide"],
      description: "Taste the authentic flavors of Cox's Bazar through our guided food tour.",
      highlights: ["Local Cuisine", "Street Food", "Cultural Experience"],
      inclusions: ["Food Tastings", "Guide", "Transportation"],
      exclusions: ["Additional Food", "Beverages"],
      cancellationPolicy: "Free cancellation up to 6 hours before tour",
      instantConfirmation: true,
      bestPriceGuarantee: true
    },
    {
      id: "6",
      title: "Cox's Bazar Photography Workshop",
      image: "/assets/images/packages/p1-6.webp",
      location: "Cox's Bazar, Bangladesh",
      duration: "2 Days",
      groupSize: "3-8 People",
      price: 110,
      rating: 4.8,
      reviewCount: 45,
      category: "Photography Tours",
      isFavorite: false,
      features: ["Professional Guide", "Equipment", "Editing Session", "Location Access"],
      description: "Capture stunning moments with our professional photography workshop.",
      highlights: ["Professional Guidance", "Equipment Provided", "Editing Session"],
      inclusions: ["Professional Guide", "Equipment", "Transportation", "Meals"],
      exclusions: ["Personal Camera", "Memory Cards"],
      cancellationPolicy: "Free cancellation up to 48 hours before tour",
      instantConfirmation: true,
      bestPriceGuarantee: true
    },
    {
      id: "7",
      title: "Cox's Bazar Sunset & Night Tour",
      image: "/assets/images/packages/p1-7.webp",
      location: "Cox's Bazar, Bangladesh",
      duration: "1 Day",
      groupSize: "2-12 People",
      price: 65,
      rating: 4.4,
      reviewCount: 92,
      category: "Evening Tours",
      isFavorite: false,
      features: ["Sunset Viewing", "Night Activities", "Local Entertainment", "Dinner"],
      description: "Experience the magical sunset and vibrant nightlife of Cox's Bazar.",
      highlights: ["Sunset Views", "Night Activities", "Local Entertainment"],
      inclusions: ["Transportation", "Guide", "Dinner", "Entertainment"],
      exclusions: ["Personal Expenses", "Additional Drinks"],
      cancellationPolicy: "Free cancellation up to 12 hours before tour",
      instantConfirmation: true,
      bestPriceGuarantee: true
    },
    {
      id: "8",
      title: "Cox's Bazar Water Sports Adventure",
      image: "/assets/images/packages/p1-8.webp",
      location: "Cox's Bazar, Bangladesh",
      duration: "1 Day",
      groupSize: "2-8 People",
      price: 90,
      rating: 4.6,
      reviewCount: 134,
      category: "Water Sports",
      isFavorite: true,
      features: ["Jet Ski", "Parasailing", "Banana Boat", "Safety Equipment"],
      description: "Get your adrenaline pumping with exciting water sports activities.",
      highlights: ["Jet Skiing", "Parasailing", "Water Activities"],
      inclusions: ["Equipment", "Safety Gear", "Instructor", "Transportation"],
      exclusions: ["Personal Items", "Photos/Videos"],
      cancellationPolicy: "Free cancellation up to 24 hours before tour",
      instantConfirmation: true,
      bestPriceGuarantee: true
    }
  ],
  
  categories: [
    "Adventure Tours",
    "Beach Activities", 
    "Cultural Tours",
    "Day Trips",
    "Water Sports",
    "Food Tours",
    "Photography Tours",
    "Wildlife Tours",
    "Evening Tours",
    "Nature Tours"
  ],
  
  durations: [
    "Half Day (2-4 hours)",
    "Full Day (8+ hours)",
    "2-3 Days",
    "4-7 Days",
    "1 Week+"
  ],
  
  priceRanges: [
    { label: "Under $50", min: 0, max: 50 },
    { label: "$50 - $100", min: 50, max: 100 },
    { label: "$100 - $200", min: 100, max: 200 },
    { label: "$200 - $300", min: 200, max: 300 },
    { label: "Over $300", min: 300, max: 1000 }
  ],
  
  ratings: [
    { value: "5", label: "5 Stars & Up" },
    { value: "4", label: "4 Stars & Up" },
    { value: "3", label: "3 Stars & Up" },
    { value: "2", label: "2 Stars & Up" }
  ],
  
  specialOffers: [
    "Free Cancellation",
    "Instant Confirmation", 
    "Best Price Guarantee",
    "Mobile Voucher",
    "Skip the Line",
    "Group Discounts"
  ],
  
  sortOptions: [
    { value: "popular", label: "Most Popular" },
    { value: "price-low", label: "Price: Low to High" },
    { value: "price-high", label: "Price: High to Low" },
    { value: "rating", label: "Highest Rated" },
    { value: "duration", label: "Duration" },
    { value: "newest", label: "Newest First" }
  ]
};

export default TravelListingData;
